/*
 *  glyph-sprite-map.ts — DisplayGlyph/TileType → sprite region for tile rendering
 *  brogue-ts
 *
 *  Reads sprite-manifest.json (generated by tools/generate-master-spritesheet.mjs)
 *  to build maps from TileType/DisplayGlyph to SpriteRef coordinates in the
 *  packed master spritesheet. Autotile variants remain on separate per-group
 *  sheets (e.g. WallAutotile).
 */

import { DisplayGlyph, TileType } from "../types/enums.js";
import {
  getConnectionGroupInfo,
  AUTOTILE_VARIANT_COUNT,
  buildVariantToWangBlob,
} from "./autotile.js";
import defaultManifest from "../../assets/tilesets/sprite-manifest.json";
import defaultAssignments from "../../assets/tilesets/assignments.json";

export interface SpriteRef {
  sheetKey: string;
  tileX: number;
  tileY: number;
}

export interface SpriteManifest {
  tiles: Record<string, { x: number; y: number }>;
  glyphs: Record<string, { x: number; y: number }>;
}

interface AutotileAssignment {
  sheet: string;
  x: number;
  y: number;
}

export interface AssignmentsData {
  autotile?: Record<string, AutotileAssignment[]>;
}

export const MASTER_SHEET_KEY = "master";

/**
 * Build the TileType → sprite lookup from the master spritesheet manifest.
 * Unmapped TileTypes fall back to the DisplayGlyph-based sprite in the renderer.
 * Pass a manifest to use a freshly-fetched one (HMR); omit for the static import.
 */
export function buildTileTypeSpriteMap(
  manifest: SpriteManifest = defaultManifest,
): Map<TileType, SpriteRef> {
  const m = new Map<TileType, SpriteRef>();
  for (const [name, coords] of Object.entries(manifest.tiles)) {
    const tt = TileType[name as keyof typeof TileType];
    if (tt !== undefined && typeof tt === "number") {
      m.set(tt, {
        sheetKey: MASTER_SHEET_KEY,
        tileX: coords.x,
        tileY: coords.y,
      });
    }
  }
  return m;
}

/**
 * Build a 47-element variant array from an 8×6 spritesheet grid.
 * Grid is indexed left-to-right, top-to-bottom by variant index.
 */
function autotileVariants(sheetKey: string): SpriteRef[] {
  const variants: SpriteRef[] = [];
  for (let v = 0; v < AUTOTILE_VARIANT_COUNT; v++) {
    variants.push({ sheetKey, tileX: v % 8, tileY: Math.floor(v / 8) });
  }
  return variants;
}

/** Lazily cached Wang Blob variant→grid mapping. */
let wangBlobMap: Map<number, { col: number; row: number }> | null = null;

/**
 * Build a 47-element variant array from a 7×7 Wang Blob spritesheet.
 * Each variant index maps to its spatial position in the Wang Blob
 * layout, where connected tiles are visually adjacent.
 */
function wangBlobVariants(sheetKey: string): SpriteRef[] {
  if (!wangBlobMap) wangBlobMap = buildVariantToWangBlob();
  const variants: SpriteRef[] = [];
  for (let v = 0; v < AUTOTILE_VARIANT_COUNT; v++) {
    const pos = wangBlobMap.get(v);
    if (pos) {
      variants.push({ sheetKey, tileX: pos.col, tileY: pos.row });
    } else {
      variants.push({ sheetKey, tileX: 0, tileY: 0 });
    }
  }
  return variants;
}

type AutotileFormat = "grid" | "wang-blob";

interface AutotileSheetDef {
  sheet: string;
  format: AutotileFormat;
}

/**
 * Autotile spritesheets keyed by connection group name. When a sheet
 * exists for a group, wall-like TileTypes in that group use its 47
 * variants. Types in AUTOTILE_SKIP keep their own sprite — they
 * participate in the connection group (so neighbors see them as
 * connected) but render with their distinct sprite, not the autotile
 * sheet.
 *
 * format "grid" = standard 8×6 sequential layout.
 * format "wang-blob" = 7×7 Wang Blob spatial layout.
 */
const AUTOTILE_SHEETS: Record<string, AutotileSheetDef> = {
  WALL: { sheet: "WallAutotile", format: "grid" },
  FLOOR: { sheet: "FloorAutotile", format: "grid" },
  CHASM: { sheet: "ChasmAutotile", format: "grid" },
};

/** Map kebab-case sheet names from assignments.json to PascalCase tileset keys. */
const SHEET_NAME_MAP: Record<string, string> = {
  "wall-autotile": "WallAutotile",
  "floor-autotile": "FloorAutotile",
  "chasm-autotile": "ChasmAutotile",
};

const AUTOTILE_SKIP = new Set<TileType>([
  TileType.DOOR,
  TileType.OPEN_DOOR,
  TileType.LOCKED_DOOR,
  TileType.PORTCULLIS_CLOSED,
  TileType.PORTCULLIS_DORMANT,
  TileType.WOODEN_BARRICADE,
  TileType.MUD_DOORWAY,
  TileType.TURRET_DORMANT,
  TileType.OPEN_IRON_DOOR_INERT,
]);

/**
 * Convert per-variant assignments from assignments.json into SpriteRef[].
 * Returns undefined if the group has no explicit assignments.
 */
function assignmentVariants(
  groupName: string,
  assignments: AssignmentsData,
): SpriteRef[] | undefined {
  const entries = assignments.autotile?.[groupName];
  if (!entries || entries.length !== AUTOTILE_VARIANT_COUNT) return undefined;
  return entries.map((a) => ({
    sheetKey: SHEET_NAME_MAP[a.sheet] ?? a.sheet,
    tileX: a.x,
    tileY: a.y,
  }));
}

/**
 * Resolve the 47-variant array for a connection group: use explicit
 * per-variant assignments from assignments.json if available, otherwise
 * fall back to the grid layout determined by the sheet's format.
 */
function resolveGroupVariants(
  groupName: string,
  sheetDef: AutotileSheetDef,
  assignments: AssignmentsData,
  cache: Map<string, SpriteRef[]>,
): SpriteRef[] {
  const cacheKey = `${groupName}:${sheetDef.sheet}`;
  let variants = cache.get(cacheKey);
  if (variants) return variants;
  variants =
    assignmentVariants(groupName, assignments) ??
    (sheetDef.format === "wang-blob"
      ? wangBlobVariants(sheetDef.sheet)
      : autotileVariants(sheetDef.sheet));
  cache.set(cacheKey, variants);
  return variants;
}

/**
 * Build the autotile variant map: for each connectable TileType, create a
 * 47-element array. If an autotile spritesheet exists for the type's
 * connection group, use distinct per-variant refs from the sheet — either
 * from explicit assignments.json entries or the standard 8x6 grid layout.
 * Types in AUTOTILE_SKIP get placeholder fills so they keep their own
 * sprite. Remaining types without a sheet also get placeholder fills.
 */
export function buildAutotileVariantMap(
  tileTypeSpriteMap: Map<TileType, SpriteRef>,
  assignments: AssignmentsData = defaultAssignments,
): Map<TileType, SpriteRef[]> {
  const map = new Map<TileType, SpriteRef[]>();
  const variantCache = new Map<string, SpriteRef[]>();

  // First pass: tile types present in the manifest
  for (const [tileType, spriteRef] of tileTypeSpriteMap) {
    const groupInfo = getConnectionGroupInfo(tileType);
    if (!groupInfo) continue;
    const sheetDef = AUTOTILE_SHEETS[groupInfo.group];
    if (sheetDef && !AUTOTILE_SKIP.has(tileType)) {
      map.set(
        tileType,
        resolveGroupVariants(
          groupInfo.group,
          sheetDef,
          assignments,
          variantCache,
        ),
      );
    } else {
      map.set(
        tileType,
        new Array<SpriteRef>(AUTOTILE_VARIANT_COUNT).fill(spriteRef),
      );
    }
  }

  // Second pass: tile types with an autotile sheet but no manifest entry
  // (e.g. FLOOR/WALL when their sprites live entirely on autotile sheets)
  for (const val of Object.values(TileType)) {
    const tt = val as TileType;
    if (typeof tt !== "number" || map.has(tt)) continue;
    const groupInfo = getConnectionGroupInfo(tt);
    if (!groupInfo) continue;
    const sheetDef = AUTOTILE_SHEETS[groupInfo.group];
    if (!sheetDef || AUTOTILE_SKIP.has(tt)) continue;
    map.set(
      tt,
      resolveGroupVariants(
        groupInfo.group,
        sheetDef,
        assignments,
        variantCache,
      ),
    );
  }

  return map;
}

/**
 * Build the glyph → sprite lookup from the master spritesheet manifest.
 * Unmapped glyphs return undefined; the renderer draws a fallback.
 * Pass a manifest to use a freshly-fetched one (HMR); omit for the static import.
 */
export function buildGlyphSpriteMap(
  manifest: SpriteManifest = defaultManifest,
): Map<DisplayGlyph, SpriteRef> {
  const m = new Map<DisplayGlyph, SpriteRef>();
  for (const [name, coords] of Object.entries(manifest.glyphs)) {
    const dg = DisplayGlyph[name as keyof typeof DisplayGlyph];
    if (dg !== undefined && typeof dg === "number") {
      m.set(dg, {
        sheetKey: MASTER_SHEET_KEY,
        tileX: coords.x,
        tileY: coords.y,
      });
    }
  }
  return m;
}

/**
 * Fetch the sprite manifest from the dev server at runtime.
 * Used during HMR to get updated tile coordinates after the assigner saves.
 */
export async function fetchSpriteManifest(): Promise<SpriteManifest> {
  const resp = await fetch(
    `/assets/tilesets/sprite-manifest.json?t=${Date.now()}`,
  );
  if (!resp.ok)
    throw new Error(`Failed to fetch sprite manifest: ${resp.status}`);
  return resp.json() as Promise<SpriteManifest>;
}
