/*
 *  tileset-loader.ts — Load master spritesheet + autotile sheets for pixel-art rendering
 *  brogue-ts
 *
 *  The master spritesheet consolidates all base sprites (TileType + DisplayGlyph)
 *  into a single packed PNG. Autotile variant sheets remain separate (one per
 *  connection group). Glyph-to-sprite mapping is in glyph-sprite-map.ts.
 *
 *  Generated by: tools/generate-master-spritesheet.mjs
 */

import MasterSheetUrl from "../../assets/tilesets/master-spritesheet.png?url";
import WallAutotileUrl from "../../assets/tilesets/autotile/wall-autotile.png?url";
import { MASTER_SHEET_KEY } from "./glyph-sprite-map.js";

const SHEET_URLS: Record<string, string> = {
  [MASTER_SHEET_KEY]: MasterSheetUrl,
  WallAutotile: WallAutotileUrl,
};

export const TILE_SIZE = 16;

/**
 * Load all tileset images. Resolves when every image has loaded.
 * Keys are sheet names ("master" for the packed spritesheet, plus
 * autotile sheet names like "WallAutotile"). Fails if any image fails.
 */
export function loadTilesetImages(): Promise<Map<string, HTMLImageElement>> {
  const map = new Map<string, HTMLImageElement>();
  const entries = Object.entries(SHEET_URLS);

  return Promise.all(
    entries.map(([name, url]) => {
      return new Promise<void>((resolve, reject) => {
        const img = new Image();
        img.onload = () => {
          map.set(name, img);
          resolve();
        };
        img.onerror = () =>
          reject(new Error(`Failed to load tileset: ${name} (${url})`));
        img.src = url;
      });
    }),
  ).then(() => map);
}
