/*
 *  monster-catalog.ts — monsterCatalog, ported from Globals.c
 *  brogue-ts
 *
 *  Defines all creature types (monsters and the player). Each entry provides
 *  base stats, abilities, flags, and visual properties for a monster type.
 *  Indexed by MonsterType enum.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 */

import type { CreatureType } from "../types/types.js";
import { MonsterType, DisplayGlyph, DungeonFeatureType, LightType, BoltType } from "../types/enums.js";
import { MonsterBehaviorFlag, MonsterAbilityFlag, MONST_TURRET } from "../types/flags.js";
import * as C from "./colors.js";

// Shorthand aliases for readability
const MBF = MonsterBehaviorFlag;
const MAF = MonsterAbilityFlag;
const G = DisplayGlyph;
const DF = DungeonFeatureType;
const LT = LightType;
const B = BoltType;

/** Helper to create a CreatureType entry with defaults for optional trailing fields. */
function m(
    monsterID: MonsterType,
    monsterName: string,
    displayChar: DisplayGlyph,
    foreColor: CreatureType["foreColor"],
    maxHP: number,
    defense: number,
    accuracy: number,
    damage: [number, number, number],
    turnsBetweenRegen: number,
    movementSpeed: number,
    attackSpeed: number,
    bloodType: DungeonFeatureType,
    intrinsicLightType: LightType | 0,
    isLarge: boolean,
    DFChance: number,
    DFType: DungeonFeatureType | 0,
    bolts: BoltType[],
    flags: number = 0,
    abilityFlags: number = 0,
): CreatureType {
    return {
        monsterID,
        monsterName,
        displayChar,
        foreColor,
        maxHP,
        defense,
        accuracy,
        damage: { lowerBound: damage[0], upperBound: damage[1], clumpFactor: damage[2] },
        turnsBetweenRegen,
        movementSpeed,
        attackSpeed,
        bloodType,
        intrinsicLightType: intrinsicLightType as LightType,
        isLarge,
        DFChance,
        DFType: DFType as DungeonFeatureType,
        bolts,
        flags,
        abilityFlags,
    };
}

/**
 * Monster catalog. Defines all creature types including the player.
 * Indexed by MonsterType enum value.
 *
 * Each entry corresponds to a row in the C `monsterCatalog` array from Globals.c.
 * The monsterID field is set to the enum value (unlike C which sets it later).
 */
export const monsterCatalog: readonly CreatureType[] = [
    // player
    m(MonsterType.MK_YOU, "you", G.G_PLAYER, C.playerInLightColor,
        30, 0, 100, [1, 2, 1], 20, 100, 100, DF.DF_RED_BLOOD, 0, false, 0, 0, [],
        MBF.MONST_MALE | MBF.MONST_FEMALE),

    // depth 1–5 monsters
    m(MonsterType.MK_RAT, "rat", G.G_RAT, C.gray,
        6, 0, 80, [1, 3, 1], 20, 100, 100, DF.DF_RED_BLOOD, 0, false, 1, DF.DF_URINE, []),
    m(MonsterType.MK_KOBOLD, "kobold", G.G_KOBOLD, C.goblinColor,
        7, 0, 80, [1, 4, 1], 20, 100, 100, DF.DF_RED_BLOOD, 0, false, 0, 0, []),
    m(MonsterType.MK_JACKAL, "jackal", G.G_JACKAL, C.jackalColor,
        8, 0, 70, [2, 4, 1], 20, 50, 100, DF.DF_RED_BLOOD, 0, false, 1, DF.DF_URINE, []),
    m(MonsterType.MK_EEL, "eel", G.G_EEL, C.eelColor,
        18, 27, 100, [3, 7, 2], 5, 50, 100, 0 as DungeonFeatureType, 0, false, 0, 0, [],
        MBF.MONST_RESTRICTED_TO_LIQUID | MBF.MONST_IMMUNE_TO_WATER | MBF.MONST_SUBMERGES | MBF.MONST_FLITS | MBF.MONST_NEVER_SLEEPS),
    m(MonsterType.MK_MONKEY, "monkey", G.G_MONKEY, C.ogreColor,
        12, 17, 100, [1, 3, 1], 20, 100, 100, DF.DF_RED_BLOOD, 0, false, 1, DF.DF_URINE, [],
        0, MAF.MA_HIT_STEAL_FLEE),
    m(MonsterType.MK_BLOAT, "bloat", G.G_BLOAT, C.poisonGasColor,
        4, 0, 100, [0, 0, 0], 5, 100, 100, DF.DF_PURPLE_BLOOD, 0, false, 0, DF.DF_BLOAT_DEATH, [],
        MBF.MONST_FLIES | MBF.MONST_FLITS, MAF.MA_KAMIKAZE | MAF.MA_DF_ON_DEATH),
    m(MonsterType.MK_PIT_BLOAT, "pit bloat", G.G_BLOAT, C.lightBlue,
        4, 0, 100, [0, 0, 0], 5, 100, 100, DF.DF_PURPLE_BLOOD, 0, false, 0, DF.DF_HOLE_POTION, [],
        MBF.MONST_FLIES | MBF.MONST_FLITS, MAF.MA_KAMIKAZE | MAF.MA_DF_ON_DEATH),
    m(MonsterType.MK_GOBLIN, "goblin", G.G_GOBLIN, C.goblinColor,
        15, 10, 70, [2, 5, 1], 20, 100, 100, DF.DF_RED_BLOOD, 0, false, 0, 0, [],
        0, MAF.MA_ATTACKS_PENETRATE | MAF.MA_AVOID_CORRIDORS),
    m(MonsterType.MK_GOBLIN_CONJURER, "goblin conjurer", G.G_GOBLIN_MAGIC, C.goblinConjurerColor,
        10, 10, 70, [2, 4, 1], 20, 100, 100, DF.DF_RED_BLOOD, 0, false, 0, 0, [],
        MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_CAST_SPELLS_SLOWLY | MBF.MONST_CARRY_ITEM_25,
        MAF.MA_CAST_SUMMON | MAF.MA_AVOID_CORRIDORS),
    m(MonsterType.MK_GOBLIN_MYSTIC, "goblin mystic", G.G_GOBLIN_MAGIC, C.goblinMysticColor,
        10, 10, 70, [2, 4, 1], 20, 100, 100, DF.DF_RED_BLOOD, 0, false, 0, 0, [B.SHIELDING],
        MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_CARRY_ITEM_25, MAF.MA_AVOID_CORRIDORS),
    m(MonsterType.MK_GOBLIN_TOTEM, "goblin totem", G.G_TOTEM, C.orange,
        30, 0, 0, [0, 0, 0], 0, 100, 300, DF.DF_RUBBLE_BLOOD, LT.IMP_LIGHT, false, 0, 0, [B.HASTE, B.SPARK],
        MONST_TURRET, 0),
    m(MonsterType.MK_PINK_JELLY, "pink jelly", G.G_JELLY, C.pinkJellyColor,
        50, 0, 85, [1, 3, 1], 0, 100, 100, DF.DF_PURPLE_BLOOD, 0, true, 0, 0, [],
        MBF.MONST_NEVER_SLEEPS, MAF.MA_CLONE_SELF_ON_DEFEND),
    m(MonsterType.MK_TOAD, "toad", G.G_TOAD, C.toadColor,
        18, 0, 90, [1, 4, 1], 10, 100, 100, DF.DF_GREEN_BLOOD, 0, false, 0, 0, [],
        0, MAF.MA_HIT_HALLUCINATE),
    m(MonsterType.MK_VAMPIRE_BAT, "vampire bat", G.G_BAT, C.gray,
        18, 25, 100, [2, 6, 1], 20, 50, 100, DF.DF_RED_BLOOD, 0, false, 0, 0, [],
        MBF.MONST_FLIES | MBF.MONST_FLITS, MAF.MA_TRANSFERENCE),
    m(MonsterType.MK_ARROW_TURRET, "arrow turret", G.G_TURRET, C.black,
        30, 0, 90, [2, 6, 1], 0, 100, 250, 0 as DungeonFeatureType, 0, false, 0, 0, [B.DISTANCE_ATTACK],
        MONST_TURRET, 0),
    m(MonsterType.MK_ACID_MOUND, "acid mound", G.G_MOUND, C.acidBackColor,
        15, 10, 70, [1, 3, 1], 5, 100, 100, DF.DF_ACID_BLOOD, 0, false, 0, 0, [],
        MBF.MONST_DEFEND_DEGRADE_WEAPON, MAF.MA_HIT_DEGRADE_ARMOR),
    m(MonsterType.MK_CENTIPEDE, "centipede", G.G_CENTIPEDE, C.centipedeColor,
        20, 20, 80, [4, 12, 1], 20, 100, 100, DF.DF_GREEN_BLOOD, 0, false, 0, 0, [],
        0, MAF.MA_CAUSES_WEAKNESS),
    m(MonsterType.MK_OGRE, "ogre", G.G_OGRE, C.ogreColor,
        55, 60, 125, [9, 13, 2], 20, 100, 200, DF.DF_RED_BLOOD, 0, true, 0, 0, [],
        MBF.MONST_MALE | MBF.MONST_FEMALE, MAF.MA_AVOID_CORRIDORS | MAF.MA_ATTACKS_STAGGER),
    m(MonsterType.MK_BOG_MONSTER, "bog monster", G.G_BOG_MONSTER, C.krakenColor,
        55, 60, 5000, [3, 4, 1], 3, 200, 100, 0 as DungeonFeatureType, 0, true, 0, 0, [],
        MBF.MONST_RESTRICTED_TO_LIQUID | MBF.MONST_SUBMERGES | MBF.MONST_FLITS | MBF.MONST_FLEES_NEAR_DEATH,
        MAF.MA_SEIZES),
    m(MonsterType.MK_OGRE_TOTEM, "ogre totem", G.G_TOTEM, C.green,
        70, 0, 0, [0, 0, 0], 0, 100, 400, DF.DF_RUBBLE_BLOOD, LT.LICH_LIGHT, false, 0, 0, [B.HEALING, B.SLOW_2],
        MONST_TURRET, 0),
    m(MonsterType.MK_SPIDER, "spider", G.G_SPIDER, C.white,
        20, 70, 90, [3, 4, 2], 20, 100, 200, DF.DF_GREEN_BLOOD, 0, false, 0, 0, [B.SPIDERWEB],
        MBF.MONST_IMMUNE_TO_WEBS | MBF.MONST_CAST_SPELLS_SLOWLY | MBF.MONST_ALWAYS_USE_ABILITY,
        MAF.MA_POISONS),
    m(MonsterType.MK_SPARK_TURRET, "spark turret", G.G_TURRET, C.lightningColor,
        80, 0, 100, [0, 0, 0], 0, 100, 150, 0 as DungeonFeatureType, LT.SPARK_TURRET_LIGHT, false, 0, 0, [B.SPARK],
        MONST_TURRET, 0),
    m(MonsterType.MK_WILL_O_THE_WISP, "wisp", G.G_WISP, C.wispLightColor,
        10, 90, 100, [0, 0, 0], 5, 100, 100, DF.DF_ASH_BLOOD, LT.WISP_LIGHT, false, 0, 0, [],
        MBF.MONST_IMMUNE_TO_FIRE | MBF.MONST_FLIES | MBF.MONST_FLITS | MBF.MONST_NEVER_SLEEPS | MBF.MONST_FIERY | MBF.MONST_DIES_IF_NEGATED,
        MAF.MA_HIT_BURN),
    m(MonsterType.MK_WRAITH, "wraith", G.G_WRAITH, C.wraithColor,
        50, 60, 120, [6, 13, 2], 5, 50, 100, DF.DF_GREEN_BLOOD, 0, true, 0, 0, [],
        MBF.MONST_FLEES_NEAR_DEATH),
    m(MonsterType.MK_ZOMBIE, "zombie", G.G_ZOMBIE, C.vomitColor,
        80, 0, 120, [7, 12, 1], 0, 100, 100, DF.DF_ROT_GAS_BLOOD, 0, true, 100, DF.DF_ROT_GAS_PUFF, []),
    m(MonsterType.MK_TROLL, "troll", G.G_TROLL, C.trollColor,
        65, 70, 125, [10, 15, 3], 1, 100, 100, DF.DF_RED_BLOOD, 0, true, 0, 0, [],
        MBF.MONST_MALE | MBF.MONST_FEMALE),
    m(MonsterType.MK_OGRE_SHAMAN, "ogre shaman", G.G_OGRE_MAGIC, C.green,
        45, 40, 100, [5, 9, 1], 20, 100, 200, DF.DF_RED_BLOOD, 0, true, 0, 0, [B.HASTE, B.SPARK],
        MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_CAST_SPELLS_SLOWLY | MBF.MONST_MALE | MBF.MONST_FEMALE,
        MAF.MA_CAST_SUMMON | MAF.MA_AVOID_CORRIDORS),
    m(MonsterType.MK_NAGA, "naga", G.G_NAGA, C.trollColor,
        75, 70, 150, [7, 11, 4], 10, 100, 100, DF.DF_GREEN_BLOOD, 0, true, 100, DF.DF_PUDDLE, [],
        MBF.MONST_IMMUNE_TO_WATER | MBF.MONST_SUBMERGES | MBF.MONST_NEVER_SLEEPS | MBF.MONST_FEMALE,
        MAF.MA_ATTACKS_ALL_ADJACENT),
    m(MonsterType.MK_SALAMANDER, "salamander", G.G_SALAMANDER, C.salamanderColor,
        60, 70, 150, [5, 11, 3], 10, 100, 100, DF.DF_ASH_BLOOD, LT.SALAMANDER_LIGHT, true, 100, DF.DF_SALAMANDER_FLAME, [],
        MBF.MONST_IMMUNE_TO_FIRE | MBF.MONST_SUBMERGES | MBF.MONST_NEVER_SLEEPS | MBF.MONST_FIERY | MBF.MONST_MALE,
        MAF.MA_ATTACKS_EXTEND),
    m(MonsterType.MK_EXPLOSIVE_BLOAT, "explosive bloat", G.G_BLOAT, C.orange,
        10, 0, 100, [0, 0, 0], 5, 100, 100, DF.DF_RED_BLOOD, LT.EXPLOSIVE_BLOAT_LIGHT, false, 0, DF.DF_BLOAT_EXPLOSION, [],
        MBF.MONST_FLIES | MBF.MONST_FLITS, MAF.MA_KAMIKAZE | MAF.MA_DF_ON_DEATH),
    m(MonsterType.MK_DAR_BLADEMASTER, "dar blademaster", G.G_DAR_BLADEMASTER, C.purple,
        35, 70, 160, [5, 9, 2], 20, 100, 100, DF.DF_RED_BLOOD, 0, false, 0, 0, [B.BLINKING],
        MBF.MONST_CARRY_ITEM_25 | MBF.MONST_MALE | MBF.MONST_FEMALE, MAF.MA_AVOID_CORRIDORS),
    m(MonsterType.MK_DAR_PRIESTESS, "dar priestess", G.G_DAR_PRIESTESS, C.darPriestessColor,
        20, 60, 100, [2, 5, 1], 20, 100, 100, DF.DF_RED_BLOOD, 0, false, 0, 0, [B.NEGATION, B.HEALING, B.HASTE, B.SPARK],
        MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_CARRY_ITEM_25 | MBF.MONST_FEMALE, MAF.MA_AVOID_CORRIDORS),
    m(MonsterType.MK_DAR_BATTLEMAGE, "dar battlemage", G.G_DAR_BATTLEMAGE, C.darMageColor,
        20, 60, 100, [1, 3, 1], 20, 100, 100, DF.DF_RED_BLOOD, 0, false, 0, 0, [B.FIRE, B.SLOW_2, B.DISCORD],
        MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_CARRY_ITEM_25 | MBF.MONST_MALE | MBF.MONST_FEMALE,
        MAF.MA_AVOID_CORRIDORS),
    m(MonsterType.MK_ACID_JELLY, "acidic jelly", G.G_JELLY, C.acidBackColor,
        60, 0, 115, [2, 6, 1], 0, 100, 100, DF.DF_ACID_BLOOD, 0, true, 0, 0, [],
        MBF.MONST_DEFEND_DEGRADE_WEAPON, MAF.MA_HIT_DEGRADE_ARMOR | MAF.MA_CLONE_SELF_ON_DEFEND),
    m(MonsterType.MK_CENTAUR, "centaur", G.G_CENTAUR, C.tanColor,
        35, 50, 175, [4, 8, 2], 20, 50, 100, DF.DF_RED_BLOOD, 0, true, 0, 0, [B.DISTANCE_ATTACK],
        MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_MALE, 0),
    m(MonsterType.MK_UNDERWORM, "underworm", G.G_UNDERWORM, C.wormColor,
        80, 40, 160, [18, 22, 2], 3, 150, 200, DF.DF_WORM_BLOOD, 0, true, 0, 0, [],
        MBF.MONST_NEVER_SLEEPS),
    m(MonsterType.MK_SENTINEL, "sentinel", G.G_GUARDIAN, C.sentinelColor,
        50, 0, 0, [0, 0, 0], 0, 100, 175, DF.DF_RUBBLE_BLOOD, LT.SENTINEL_LIGHT, false, 0, 0, [B.HEALING, B.SPARK],
        MONST_TURRET | MBF.MONST_CAST_SPELLS_SLOWLY | MBF.MONST_DIES_IF_NEGATED, 0),
    m(MonsterType.MK_DART_TURRET, "dart turret", G.G_TURRET, C.centipedeColor,
        20, 0, 140, [1, 2, 1], 0, 100, 250, 0 as DungeonFeatureType, 0, false, 0, 0, [B.POISON_DART],
        MONST_TURRET, MAF.MA_CAUSES_WEAKNESS),
    m(MonsterType.MK_KRAKEN, "kraken", G.G_KRAKEN, C.krakenColor,
        120, 0, 150, [15, 20, 3], 1, 50, 100, 0 as DungeonFeatureType, 0, true, 0, 0, [],
        MBF.MONST_RESTRICTED_TO_LIQUID | MBF.MONST_IMMUNE_TO_WATER | MBF.MONST_SUBMERGES | MBF.MONST_FLITS | MBF.MONST_NEVER_SLEEPS | MBF.MONST_FLEES_NEAR_DEATH,
        MAF.MA_SEIZES),
    m(MonsterType.MK_LICH, "lich", G.G_LICH, C.white,
        35, 80, 175, [2, 6, 1], 0, 100, 100, DF.DF_ASH_BLOOD, LT.LICH_LIGHT, true, 0, 0, [B.FIRE],
        MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_CARRY_ITEM_25 | MBF.MONST_NO_POLYMORPH,
        MAF.MA_CAST_SUMMON),
    m(MonsterType.MK_PHYLACTERY, "phylactery", G.G_EGG, C.lichLightColor,
        30, 0, 0, [0, 0, 0], 0, 100, 150, DF.DF_RUBBLE_BLOOD, LT.LICH_LIGHT, false, 0, 0, [],
        MBF.MONST_IMMUNE_TO_WEBS | MBF.MONST_NEVER_SLEEPS | MBF.MONST_IMMOBILE | MBF.MONST_INANIMATE | MBF.MONST_ALWAYS_HUNTING | MBF.MONST_WILL_NOT_USE_STAIRS | MBF.MONST_DIES_IF_NEGATED,
        MAF.MA_CAST_SUMMON | MAF.MA_ENTER_SUMMONS),
    m(MonsterType.MK_PIXIE, "pixie", G.G_PIXIE, C.pixieColor,
        10, 90, 100, [1, 3, 1], 20, 50, 100, DF.DF_GREEN_BLOOD, LT.PIXIE_LIGHT, false, 0, 0, [B.NEGATION, B.SLOW_2, B.DISCORD, B.SPARK],
        MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_FLIES | MBF.MONST_FLITS | MBF.MONST_MALE | MBF.MONST_FEMALE, 0),
    m(MonsterType.MK_PHANTOM, "phantom", G.G_PHANTOM, C.ectoplasmColor,
        35, 70, 160, [12, 18, 4], 0, 50, 200, DF.DF_ECTOPLASM_BLOOD, 0, true, 2, DF.DF_ECTOPLASM_DROPLET, [],
        MBF.MONST_INVISIBLE | MBF.MONST_FLITS | MBF.MONST_FLIES | MBF.MONST_IMMUNE_TO_WEBS),
    m(MonsterType.MK_FLAME_TURRET, "flame turret", G.G_TURRET, C.lavaForeColor,
        40, 0, 150, [1, 2, 1], 0, 100, 250, 0 as DungeonFeatureType, LT.LAVA_LIGHT, false, 0, 0, [B.FIRE],
        MONST_TURRET, 0),
    m(MonsterType.MK_IMP, "imp", G.G_IMP, C.pink,
        35, 90, 225, [4, 9, 2], 10, 100, 100, DF.DF_GREEN_BLOOD, LT.IMP_LIGHT, false, 0, 0, [B.BLINKING],
        0, MAF.MA_HIT_STEAL_FLEE),
    m(MonsterType.MK_FURY, "fury", G.G_FURY, C.darkRed,
        19, 90, 200, [6, 11, 4], 20, 50, 100, DF.DF_RED_BLOOD, 0, false, 0, 0, [],
        MBF.MONST_NEVER_SLEEPS | MBF.MONST_FLIES),
    m(MonsterType.MK_REVENANT, "revenant", G.G_REVENANT, C.ectoplasmColor,
        30, 0, 200, [15, 20, 5], 0, 100, 100, DF.DF_ECTOPLASM_BLOOD, 0, true, 0, 0, [],
        MBF.MONST_IMMUNE_TO_WEAPONS),
    m(MonsterType.MK_TENTACLE_HORROR, "tentacle horror", G.G_TENTACLE_HORROR, C.centipedeColor,
        120, 95, 225, [25, 35, 3], 1, 100, 100, DF.DF_PURPLE_BLOOD, 0, true, 0, 0, []),
    m(MonsterType.MK_GOLEM, "golem", G.G_GOLEM, C.gray,
        400, 70, 225, [4, 8, 1], 0, 100, 100, DF.DF_RUBBLE_BLOOD, 0, true, 0, 0, [],
        MBF.MONST_REFLECT_50 | MBF.MONST_DIES_IF_NEGATED),
    m(MonsterType.MK_DRAGON, "dragon", G.G_DRAGON, C.dragonColor,
        150, 90, 250, [25, 50, 4], 20, 50, 200, DF.DF_GREEN_BLOOD, 0, true, 0, 0, [B.DRAGONFIRE],
        MBF.MONST_IMMUNE_TO_FIRE | MBF.MONST_CARRY_ITEM_100, MAF.MA_ATTACKS_ALL_ADJACENT),

    // bosses
    m(MonsterType.MK_GOBLIN_CHIEFTAN, "goblin warlord", G.G_GOBLIN_CHIEFTAN, C.blue,
        30, 17, 100, [3, 6, 1], 20, 100, 100, DF.DF_RED_BLOOD, 0, false, 0, 0, [],
        MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_CARRY_ITEM_25,
        MAF.MA_CAST_SUMMON | MAF.MA_ATTACKS_PENETRATE | MAF.MA_AVOID_CORRIDORS),
    m(MonsterType.MK_BLACK_JELLY, "black jelly", G.G_JELLY, C.black,
        120, 0, 130, [3, 8, 1], 0, 100, 100, DF.DF_PURPLE_BLOOD, 0, true, 0, 0, [],
        0, MAF.MA_CLONE_SELF_ON_DEFEND),
    m(MonsterType.MK_VAMPIRE, "vampire", G.G_VAMPIRE, C.white,
        75, 60, 120, [4, 15, 2], 6, 50, 100, DF.DF_RED_BLOOD, 0, true, 0, DF.DF_BLOOD_EXPLOSION, [B.BLINKING, B.DISCORD],
        MBF.MONST_FLEES_NEAR_DEATH | MBF.MONST_MALE,
        MAF.MA_TRANSFERENCE | MAF.MA_DF_ON_DEATH | MAF.MA_CAST_SUMMON | MAF.MA_ENTER_SUMMONS),
    m(MonsterType.MK_FLAMEDANCER, "flamedancer", G.G_FLAMEDANCER, C.white,
        65, 80, 120, [3, 8, 2], 0, 100, 100, DF.DF_EMBER_BLOOD, LT.FLAMEDANCER_LIGHT, true, 100, DF.DF_FLAMEDANCER_CORONA, [B.FIRE],
        MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_IMMUNE_TO_FIRE | MBF.MONST_FIERY, MAF.MA_HIT_BURN),

    // special effect monsters
    m(MonsterType.MK_SPECTRAL_BLADE, "spectral blade", G.G_WEAPON, C.spectralBladeColor,
        1, 0, 150, [1, 1, 1], 0, 50, 100, 0 as DungeonFeatureType, LT.SPECTRAL_BLADE_LIGHT, false, 0, 0, [],
        MBF.MONST_INANIMATE | MBF.MONST_NEVER_SLEEPS | MBF.MONST_FLIES | MBF.MONST_WILL_NOT_USE_STAIRS | MBF.MONST_DIES_IF_NEGATED | MBF.MONST_IMMUNE_TO_WEBS | MBF.MONST_NOT_LISTED_IN_SIDEBAR),
    m(MonsterType.MK_SPECTRAL_IMAGE, "spectral sword", G.G_WEAPON, C.spectralImageColor,
        1, 0, 150, [1, 1, 1], 0, 50, 100, 0 as DungeonFeatureType, LT.SPECTRAL_IMAGE_LIGHT, false, 0, 0, [],
        MBF.MONST_INANIMATE | MBF.MONST_NEVER_SLEEPS | MBF.MONST_FLIES | MBF.MONST_WILL_NOT_USE_STAIRS | MBF.MONST_DIES_IF_NEGATED | MBF.MONST_IMMUNE_TO_WEBS),
    m(MonsterType.MK_GUARDIAN, "stone guardian", G.G_GUARDIAN, C.white,
        1000, 0, 200, [12, 17, 2], 0, 100, 100, DF.DF_RUBBLE, 0, false, 100, DF.DF_GUARDIAN_STEP, [],
        MBF.MONST_INANIMATE | MBF.MONST_NEVER_SLEEPS | MBF.MONST_ALWAYS_HUNTING | MBF.MONST_IMMUNE_TO_FIRE | MBF.MONST_IMMUNE_TO_WEAPONS | MBF.MONST_WILL_NOT_USE_STAIRS | MBF.MONST_DIES_IF_NEGATED | MBF.MONST_ALWAYS_USE_ABILITY | MBF.MONST_GETS_TURN_ON_ACTIVATION,
        MAF.MA_REFLECT_100),
    m(MonsterType.MK_WINGED_GUARDIAN, "winged guardian", G.G_WINGED_GUARDIAN, C.blue,
        1000, 0, 200, [12, 17, 2], 0, 100, 100, DF.DF_RUBBLE, 0, false, 100, DF.DF_SILENT_GLYPH_GLOW, [B.BLINKING],
        MBF.MONST_INANIMATE | MBF.MONST_NEVER_SLEEPS | MBF.MONST_ALWAYS_HUNTING | MBF.MONST_IMMUNE_TO_FIRE | MBF.MONST_IMMUNE_TO_WEAPONS | MBF.MONST_WILL_NOT_USE_STAIRS | MBF.MONST_DIES_IF_NEGATED | MBF.MONST_GETS_TURN_ON_ACTIVATION | MBF.MONST_ALWAYS_USE_ABILITY,
        MAF.MA_REFLECT_100),
    m(MonsterType.MK_CHARM_GUARDIAN, "guardian spirit", G.G_GUARDIAN, C.spectralImageColor,
        1000, 0, 200, [5, 12, 2], 0, 100, 100, 0 as DungeonFeatureType, LT.SPECTRAL_IMAGE_LIGHT, false, 100, 0, [],
        MBF.MONST_INANIMATE | MBF.MONST_NEVER_SLEEPS | MBF.MONST_IMMUNE_TO_FIRE | MBF.MONST_IMMUNE_TO_WEAPONS | MBF.MONST_DIES_IF_NEGATED | MBF.MONST_ALWAYS_USE_ABILITY,
        MAF.MA_REFLECT_100),
    m(MonsterType.MK_WARDEN_OF_YENDOR, "Warden of Yendor", G.G_WARDEN, C.yendorLightColor,
        1000, 0, 300, [12, 17, 2], 0, 200, 200, DF.DF_RUBBLE, LT.YENDOR_LIGHT, true, 100, 0, [],
        MBF.MONST_NEVER_SLEEPS | MBF.MONST_ALWAYS_HUNTING | MBF.MONST_INVULNERABLE | MBF.MONST_NO_POLYMORPH),
    m(MonsterType.MK_ELDRITCH_TOTEM, "eldritch totem", G.G_TOTEM, C.glyphColor,
        80, 0, 0, [0, 0, 0], 0, 100, 100, DF.DF_RUBBLE_BLOOD, 0, false, 0, 0, [],
        MBF.MONST_IMMUNE_TO_WEBS | MBF.MONST_NEVER_SLEEPS | MBF.MONST_IMMOBILE | MBF.MONST_INANIMATE | MBF.MONST_ALWAYS_HUNTING | MBF.MONST_WILL_NOT_USE_STAIRS | MBF.MONST_GETS_TURN_ON_ACTIVATION | MBF.MONST_ALWAYS_USE_ABILITY,
        MAF.MA_CAST_SUMMON),
    m(MonsterType.MK_MIRRORED_TOTEM, "mirrored totem", G.G_TOTEM, C.beckonColor,
        80, 0, 0, [0, 0, 0], 0, 100, 100, DF.DF_RUBBLE_BLOOD, 0, false, 100, DF.DF_MIRROR_TOTEM_STEP, [B.BECKONING],
        MBF.MONST_IMMUNE_TO_WEBS | MBF.MONST_NEVER_SLEEPS | MBF.MONST_IMMOBILE | MBF.MONST_INANIMATE | MBF.MONST_ALWAYS_HUNTING | MBF.MONST_WILL_NOT_USE_STAIRS | MBF.MONST_GETS_TURN_ON_ACTIVATION | MBF.MONST_ALWAYS_USE_ABILITY | MBF.MONST_IMMUNE_TO_WEAPONS | MBF.MONST_IMMUNE_TO_FIRE,
        MAF.MA_REFLECT_100),

    // legendary allies
    m(MonsterType.MK_UNICORN, "unicorn", G.G_UNICORN, C.white,
        40, 60, 175, [2, 10, 2], 20, 50, 100, DF.DF_RED_BLOOD, LT.UNICORN_LIGHT, true, 1, DF.DF_UNICORN_POOP, [B.HEALING, B.SHIELDING],
        MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_MALE | MBF.MONST_FEMALE, 0),
    m(MonsterType.MK_IFRIT, "ifrit", G.G_IFRIT, C.ifritColor,
        40, 75, 175, [5, 13, 2], 1, 50, 100, DF.DF_ASH_BLOOD, LT.IFRIT_LIGHT, true, 0, 0, [B.DISCORD],
        MBF.MONST_IMMUNE_TO_FIRE | MBF.MONST_FLIES | MBF.MONST_MALE, 0),
    m(MonsterType.MK_PHOENIX, "phoenix", G.G_PHOENIX, C.phoenixColor,
        30, 70, 175, [4, 10, 2], 0, 50, 100, DF.DF_ASH_BLOOD, LT.PHOENIX_LIGHT, true, 0, 0, [],
        MBF.MONST_IMMUNE_TO_FIRE | MBF.MONST_FLIES | MBF.MONST_NO_POLYMORPH),
    m(MonsterType.MK_PHOENIX_EGG, "phoenix egg", G.G_EGG, C.phoenixColor,
        50, 0, 0, [0, 0, 0], 0, 100, 150, DF.DF_ASH_BLOOD, LT.PHOENIX_EGG_LIGHT, false, 0, 0, [],
        MBF.MONST_IMMUNE_TO_FIRE | MBF.MONST_IMMUNE_TO_WEBS | MBF.MONST_NEVER_SLEEPS | MBF.MONST_IMMOBILE | MBF.MONST_INANIMATE | MBF.MONST_WILL_NOT_USE_STAIRS | MBF.MONST_NO_POLYMORPH | MBF.MONST_ALWAYS_HUNTING | MBF.MONST_IMMUNE_TO_WEAPONS,
        MAF.MA_CAST_SUMMON | MAF.MA_ENTER_SUMMONS),
    m(MonsterType.MK_ANCIENT_SPIRIT, "mangrove dryad", G.G_ANCIENT_SPIRIT, C.tanColor,
        70, 60, 175, [2, 8, 2], 6, 100, 100, DF.DF_ASH_BLOOD, 0, true, 0, 0, [B.ANCIENT_SPIRIT_VINES],
        MBF.MONST_IMMUNE_TO_WEBS | MBF.MONST_ALWAYS_USE_ABILITY | MBF.MONST_MAINTAINS_DISTANCE | MBF.MONST_NO_POLYMORPH | MBF.MONST_MALE | MBF.MONST_FEMALE, 0),
];
