/*
 *  dungeon-feature-catalog.ts — dungeonFeatureCatalog, ported from Globals.c
 *  brogue-ts
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 */

import type { DungeonFeature } from "../types/types.js";
import { TileType, DungeonLayer, DungeonFeatureType, LightType } from "../types/enums.js";
import { DFFlag as DFF } from "../types/flags.js";
import { DCOLS } from "../types/constants.js";
import * as C from "./colors.js";

/**
 * Dungeon feature catalog. Each entry defines a terrain feature that can be
 * spawned during dungeon generation or gameplay. Indexed by DungeonFeatureType.
 */
export const dungeonFeatureCatalog: DungeonFeature[] = [
    { // 0
        tile: TileType.NOTHING,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 1
        tile: TileType.GRANITE,
        layer: DungeonLayer.Dungeon,
        startProbability: 80,
        probabilityDecrement: 70,
        flags: DFF.DFF_CLEAR_OTHER_TERRAIN,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 2
        tile: TileType.CRYSTAL_WALL,
        layer: DungeonLayer.Dungeon,
        startProbability: 200,
        probabilityDecrement: 50,
        flags: DFF.DFF_CLEAR_OTHER_TERRAIN,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 3
        tile: TileType.LUMINESCENT_FUNGUS,
        layer: DungeonLayer.Surface,
        startProbability: 60,
        probabilityDecrement: 8,
        flags: DFF.DFF_BLOCKED_BY_OTHER_LAYERS,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 4
        tile: TileType.GRASS,
        layer: DungeonLayer.Surface,
        startProbability: 75,
        probabilityDecrement: 5,
        flags: DFF.DFF_BLOCKED_BY_OTHER_LAYERS,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 5
        tile: TileType.DEAD_GRASS,
        layer: DungeonLayer.Surface,
        startProbability: 75,
        probabilityDecrement: 5,
        flags: DFF.DFF_BLOCKED_BY_OTHER_LAYERS,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_DEAD_FOLIAGE,
        messageDisplayed: false,
    },
    { // 6
        tile: TileType.BONES,
        layer: DungeonLayer.Surface,
        startProbability: 75,
        probabilityDecrement: 23,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 7
        tile: TileType.RUBBLE,
        layer: DungeonLayer.Surface,
        startProbability: 45,
        probabilityDecrement: 23,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 8
        tile: TileType.FOLIAGE,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 33,
        flags: DFF.DFF_BLOCKED_BY_OTHER_LAYERS,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 9
        tile: TileType.FUNGUS_FOREST,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 45,
        flags: DFF.DFF_BLOCKED_BY_OTHER_LAYERS,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 10
        tile: TileType.DEAD_FOLIAGE,
        layer: DungeonLayer.Surface,
        startProbability: 50,
        probabilityDecrement: 30,
        flags: DFF.DFF_BLOCKED_BY_OTHER_LAYERS,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // misc. liquids
    { // 11
        tile: TileType.SUNLIGHT_POOL,
        layer: DungeonLayer.Liquid,
        startProbability: 65,
        probabilityDecrement: 6,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 12
        tile: TileType.DARKNESS_PATCH,
        layer: DungeonLayer.Liquid,
        startProbability: 65,
        probabilityDecrement: 11,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // Dungeon features spawned during gameplay:
    // revealed secrets
    { // 13
        tile: TileType.DOOR,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 14
        tile: TileType.GAS_TRAP_POISON,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 15
        tile: TileType.GAS_TRAP_PARALYSIS,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 16
        tile: TileType.CHASM_EDGE,
        layer: DungeonLayer.Liquid,
        startProbability: 100,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 17
        tile: TileType.TRAP_DOOR,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_CLEAR_OTHER_TERRAIN,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_SHOW_TRAPDOOR_HALO,
        messageDisplayed: false,
    },
    { // 18
        tile: TileType.GAS_TRAP_CONFUSION,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 19
        tile: TileType.FLAMETHROWER,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 20
        tile: TileType.FLOOD_TRAP,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 21
        tile: TileType.NET_TRAP,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 22
        tile: TileType.ALARM_TRAP,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // bloods
    // Start probability is actually a percentage for bloods.
    // Base probability is 15 + (damage * 2/3), and then take the given percentage of that.
    // If it's a gas, we multiply the base by an additional 100.
    // Thus to get a starting gas volume of a poison potion (1000), with a hit for 10 damage, use a starting probability of 48.
    { // 23
        tile: TileType.RED_BLOOD,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 24
        tile: TileType.GREEN_BLOOD,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 25
        tile: TileType.PURPLE_BLOOD,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 26
        tile: TileType.WORM_BLOOD,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 27
        tile: TileType.ACID_SPLATTER,
        layer: DungeonLayer.Surface,
        startProbability: 200,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 28
        tile: TileType.ASH,
        layer: DungeonLayer.Surface,
        startProbability: 50,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 29
        tile: TileType.EMBERS,
        layer: DungeonLayer.Surface,
        startProbability: 125,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 30
        tile: TileType.ECTOPLASM,
        layer: DungeonLayer.Surface,
        startProbability: 110,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 31
        tile: TileType.RUBBLE,
        layer: DungeonLayer.Surface,
        startProbability: 33,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 32
        tile: TileType.ROT_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 12,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // monster effects
    { // 33
        tile: TileType.VOMIT,
        layer: DungeonLayer.Surface,
        startProbability: 30,
        probabilityDecrement: 10,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 34
        tile: TileType.POISON_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 2000,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 35
        tile: TileType.GAS_EXPLOSION,
        layer: DungeonLayer.Surface,
        startProbability: 350,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.EXPLOSION_FLARE_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 36
        tile: TileType.RED_BLOOD,
        layer: DungeonLayer.Surface,
        startProbability: 150,
        probabilityDecrement: 30,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 37
        tile: TileType.FLAMEDANCER_FIRE,
        layer: DungeonLayer.Surface,
        startProbability: 200,
        probabilityDecrement: 75,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // mutation effects
    { // 38
        tile: TileType.GAS_EXPLOSION,
        layer: DungeonLayer.Surface,
        startProbability: 350,
        probabilityDecrement: 100,
        flags: 0,
        description: "The corpse detonates with terrifying force!",
        lightFlare: LightType.EXPLOSION_FLARE_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 39
        tile: TileType.LICHEN,
        layer: DungeonLayer.Surface,
        startProbability: 70,
        probabilityDecrement: 60,
        flags: 0,
        description: "Poisonous spores burst from the corpse!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // misc
    { // 40
        tile: TileType.NOTHING,
        layer: DungeonLayer.Gas,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_EVACUATE_CREATURES_FIRST,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 41
        tile: TileType.ROT_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 15,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 42
        tile: TileType.STEAM,
        layer: DungeonLayer.Gas,
        startProbability: 325,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 43
        tile: TileType.STEAM,
        layer: DungeonLayer.Gas,
        startProbability: 15,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 44
        tile: TileType.METHANE_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 2,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 45
        tile: TileType.EMBERS,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 46
        tile: TileType.URINE,
        layer: DungeonLayer.Surface,
        startProbability: 65,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 47
        tile: TileType.UNICORN_POOP,
        layer: DungeonLayer.Surface,
        startProbability: 65,
        probabilityDecrement: 40,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 48
        tile: TileType.PUDDLE,
        layer: DungeonLayer.Surface,
        startProbability: 13,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 49
        tile: TileType.ASH,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 50
        tile: TileType.ECTOPLASM,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 51
        tile: TileType.FORCEFIELD,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 50,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 52
        tile: TileType.FORCEFIELD_MELT,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 53
        tile: TileType.SACRED_GLYPH,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.EMPOWERMENT_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 54
        tile: TileType.LICHEN,
        layer: DungeonLayer.Surface,
        startProbability: 2,
        probabilityDecrement: 100,
        flags: DFF.DFF_BLOCKED_BY_OTHER_LAYERS,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 55
        tile: TileType.RUBBLE,
        layer: DungeonLayer.Surface,
        startProbability: 45,
        probabilityDecrement: 23,
        flags: DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 56
        tile: TileType.RUBBLE,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 57
        tile: TileType.SPIDERWEB,
        layer: DungeonLayer.Surface,
        startProbability: 15,
        probabilityDecrement: 12,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 58
        tile: TileType.SPIDERWEB,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 39,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 59
        tile: TileType.ANCIENT_SPIRIT_VINES,
        layer: DungeonLayer.Surface,
        startProbability: 75,
        probabilityDecrement: 70,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 60
        tile: TileType.ANCIENT_SPIRIT_GRASS,
        layer: DungeonLayer.Surface,
        startProbability: 50,
        probabilityDecrement: 47,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // foliage
    { // 61
        tile: TileType.TRAMPLED_FOLIAGE,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 62
        tile: TileType.DEAD_GRASS,
        layer: DungeonLayer.Surface,
        startProbability: 75,
        probabilityDecrement: 75,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 63
        tile: TileType.FOLIAGE,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_BLOCKED_BY_OTHER_LAYERS,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 64
        tile: TileType.TRAMPLED_FUNGUS_FOREST,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 65
        tile: TileType.FUNGUS_FOREST,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_BLOCKED_BY_OTHER_LAYERS,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // brimstone
    { // 66
        tile: TileType.ACTIVE_BRIMSTONE,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 67
        tile: TileType.INERT_BRIMSTONE,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_BRIMSTONE_FIRE,
        messageDisplayed: false,
    },
    // bloodwort
    { // 68
        tile: TileType.BLOODFLOWER_POD,
        layer: DungeonLayer.Surface,
        startProbability: 60,
        probabilityDecrement: 60,
        flags: DFF.DFF_EVACUATE_CREATURES_FIRST,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 69
        tile: TileType.BLOODFLOWER_POD,
        layer: DungeonLayer.Surface,
        startProbability: 10,
        probabilityDecrement: 10,
        flags: DFF.DFF_EVACUATE_CREATURES_FIRST,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 70
        tile: TileType.HEALING_CLOUD,
        layer: DungeonLayer.Gas,
        startProbability: 350,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // dewars
    { // 71
        tile: TileType.POISON_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 20000,
        probabilityDecrement: 0,
        flags: 0,
        description: "the dewar shatters and pressurized caustic gas explodes outward!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.poisonGasColor,
        effectRadius: 4,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_DEWAR_GLASS,
        messageDisplayed: false,
    },
    { // 72
        tile: TileType.CONFUSION_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 20000,
        probabilityDecrement: 0,
        flags: 0,
        description: "the dewar shatters and pressurized confusion gas explodes outward!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.confusionGasColor,
        effectRadius: 4,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_DEWAR_GLASS,
        messageDisplayed: false,
    },
    { // 73
        tile: TileType.PARALYSIS_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 20000,
        probabilityDecrement: 0,
        flags: 0,
        description: "the dewar shatters and pressurized paralytic gas explodes outward!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.pink,
        effectRadius: 4,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_DEWAR_GLASS,
        messageDisplayed: false,
    },
    { // 74
        tile: TileType.METHANE_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 20000,
        probabilityDecrement: 0,
        flags: 0,
        description: "the dewar shatters and pressurized methane gas explodes outward!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.methaneColor,
        effectRadius: 4,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_DEWAR_GLASS,
        messageDisplayed: false,
    },
    { // 75
        tile: TileType.BROKEN_GLASS,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 70,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 76
        tile: TileType.CARPET,
        layer: DungeonLayer.Dungeon,
        startProbability: 120,
        probabilityDecrement: 20,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // algae
    { // 77
        tile: TileType.DEEP_WATER_ALGAE_WELL,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_SUPERPRIORITY,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 78
        tile: TileType.DEEP_WATER_ALGAE_1,
        layer: DungeonLayer.Liquid,
        startProbability: 50,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.DEEP_WATER,
        subsequentDF: DungeonFeatureType.DF_ALGAE_2,
        messageDisplayed: false,
    },
    { // 79
        tile: TileType.DEEP_WATER_ALGAE_2,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 80
        tile: TileType.DEEP_WATER,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_SUPERPRIORITY,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // doors, item cages, altars, glyphs, guardians -- reusable machine components
    { // 81
        tile: TileType.OPEN_DOOR,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 82
        tile: TileType.DOOR,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 83
        tile: TileType.OPEN_IRON_DOOR_INERT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 84
        tile: TileType.ALTAR_CAGE_OPEN,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "the cages lift off of the altars as you approach.",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 85
        tile: TileType.ALTAR_CAGE_CLOSED,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_EVACUATE_CREATURES_FIRST,
        description: "the cages lower to cover the altars.",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 86
        tile: TileType.ALTAR_INERT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 87
        tile: TileType.FLOOR_FLOODABLE,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "the altar retracts into the ground with a grinding sound.",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 88
        tile: TileType.PORTAL_LIGHT,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_EVACUATE_CREATURES_FIRST | DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "the archway flashes, and you catch a glimpse of another world!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 89
        tile: TileType.MACHINE_GLYPH_INACTIVE,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 90
        tile: TileType.MACHINE_GLYPH,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 91
        tile: TileType.GUARDIAN_GLOW,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 92
        tile: TileType.GUARDIAN_GLOW,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "the glyph beneath you glows, and the guardians take a step!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 93
        tile: TileType.GUARDIAN_GLOW,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "the mirrored totem flashes, reflecting the red glow of the glyph beneath you.",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 94
        tile: TileType.MACHINE_GLYPH,
        layer: DungeonLayer.Dungeon,
        startProbability: 200,
        probabilityDecrement: 95,
        flags: DFF.DFF_BLOCKED_BY_OTHER_LAYERS,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 95
        tile: TileType.WALL_LEVER,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "you notice a lever hidden behind a loose stone in the wall.",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 96
        tile: TileType.WALL_LEVER_PULLED,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 97
        tile: TileType.WALL_LEVER_HIDDEN,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 98
        tile: TileType.BRIDGE_FALLING,
        layer: DungeonLayer.Liquid,
        startProbability: 200,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.BRIDGE,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 99
        tile: TileType.CHASM,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_BRIDGE_FALL_PREP,
        messageDisplayed: false,
    },
    // fire
    { // 100
        tile: TileType.PLAIN_FIRE,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 101
        tile: TileType.GAS_FIRE,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 102
        tile: TileType.GAS_EXPLOSION,
        layer: DungeonLayer.Surface,
        startProbability: 60,
        probabilityDecrement: 17,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 103
        tile: TileType.DART_EXPLOSION,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 104
        tile: TileType.BRIMSTONE_FIRE,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 105
        tile: TileType.NOTHING,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "the rope bridge snaps from the heat and plunges into the chasm!",
        lightFlare: LightType.FALLEN_TORCH_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_BRIDGE_FALL,
        messageDisplayed: false,
    },
    { // 106
        tile: TileType.PLAIN_FIRE,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 37,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 107
        tile: TileType.EMBERS,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 108
        tile: TileType.EMBERS,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 94,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 109
        tile: TileType.OBSIDIAN,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_CLEAR_LOWER_PRIORITY_TERRAIN,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 110
        tile: TileType.ITEM_FIRE,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.FALLEN_TORCH_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 111
        tile: TileType.CREATURE_FIRE,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.FALLEN_TORCH_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 112
        tile: TileType.FLOOD_WATER_SHALLOW,
        layer: DungeonLayer.Surface,
        startProbability: 225,
        probabilityDecrement: 37,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_FLOOD_2,
        messageDisplayed: false,
    },
    { // 113
        tile: TileType.FLOOD_WATER_DEEP,
        layer: DungeonLayer.Surface,
        startProbability: 175,
        probabilityDecrement: 37,
        flags: 0,
        description: "the area is flooded as water rises through imperceptible holes in the ground.",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 114
        tile: TileType.FLOOD_WATER_SHALLOW,
        layer: DungeonLayer.Surface,
        startProbability: 10,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 115
        tile: TileType.HOLE,
        layer: DungeonLayer.Surface,
        startProbability: 200,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 116
        tile: TileType.HOLE_EDGE,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // ice effects
    { // 117
        tile: TileType.ICE_DEEP,
        layer: DungeonLayer.Liquid,
        startProbability: 150,
        probabilityDecrement: 50,
        flags: DFF.DFF_EVACUATE_CREATURES_FIRST,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.DEEP_WATER,
        subsequentDF: DungeonFeatureType.DF_ALGAE_1_FREEZE,
        messageDisplayed: false,
    },
    { // 118
        tile: TileType.ICE_DEEP,
        layer: DungeonLayer.Liquid,
        startProbability: 150,
        probabilityDecrement: 50,
        flags: DFF.DFF_EVACUATE_CREATURES_FIRST,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.DEEP_WATER_ALGAE_1,
        subsequentDF: DungeonFeatureType.DF_ALGAE_2_FREEZE,
        messageDisplayed: false,
    },
    { // 119
        tile: TileType.ICE_DEEP,
        layer: DungeonLayer.Liquid,
        startProbability: 150,
        probabilityDecrement: 50,
        flags: DFF.DFF_EVACUATE_CREATURES_FIRST,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.DEEP_WATER_ALGAE_2,
        subsequentDF: DungeonFeatureType.DF_SHALLOW_WATER_FREEZE,
        messageDisplayed: false,
    },
    { // 120
        tile: TileType.ICE_DEEP_MELT,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 121
        tile: TileType.DEEP_WATER,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 122
        tile: TileType.ICE_SHALLOW,
        layer: DungeonLayer.Liquid,
        startProbability: 100,
        probabilityDecrement: 50,
        flags: DFF.DFF_EVACUATE_CREATURES_FIRST,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.SHALLOW_WATER,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 123
        tile: TileType.ICE_SHALLOW_MELT,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 124
        tile: TileType.SHALLOW_WATER,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // gas trap effects
    { // 125
        tile: TileType.POISON_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 1000,
        probabilityDecrement: 0,
        flags: 0,
        description: "a cloud of caustic gas sprays upward from the floor!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 126
        tile: TileType.CONFUSION_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 300,
        probabilityDecrement: 0,
        flags: 0,
        description: "a sparkling cloud of confusion gas sprays upward from the floor!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 127
        tile: TileType.NETTING,
        layer: DungeonLayer.Surface,
        startProbability: 300,
        probabilityDecrement: 90,
        flags: 0,
        description: "a net falls from the ceiling!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 128
        tile: TileType.NOTHING,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_AGGRAVATES_MONSTERS,
        description: "a piercing shriek echoes through the nearby rooms!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: DCOLS/2,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 129
        tile: TileType.METHANE_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 10000,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // potions
    { // 130
        tile: TileType.POISON_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 1000,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.poisonGasColor,
        effectRadius: 4,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 131
        tile: TileType.PARALYSIS_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 1000,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.pink,
        effectRadius: 4,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 132
        tile: TileType.CONFUSION_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 1000,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.confusionGasColor,
        effectRadius: 4,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 133
        tile: TileType.PLAIN_FIRE,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 37,
        flags: 0,
        description: "",
        lightFlare: LightType.EXPLOSION_FLARE_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 134
        tile: TileType.DARKNESS_CLOUD,
        layer: DungeonLayer.Gas,
        startProbability: 200,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 135
        tile: TileType.HOLE_EDGE,
        layer: DungeonLayer.Surface,
        startProbability: 300,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.darkBlue,
        effectRadius: 3,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_HOLE_2,
        messageDisplayed: false,
    },
    { // 136
        tile: TileType.LICHEN,
        layer: DungeonLayer.Surface,
        startProbability: 70,
        probabilityDecrement: 60,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // other items
    { // 137
        tile: TileType.PLAIN_FIRE,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 45,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.yellow,
        effectRadius: 3,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 138
        tile: TileType.HOLE_GLOW,
        layer: DungeonLayer.Surface,
        startProbability: 200,
        probabilityDecrement: 100,
        flags: DFF.DFF_SUBSEQ_EVERYWHERE,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.darkBlue,
        effectRadius: 3,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_STAFF_HOLE_EDGE,
        messageDisplayed: false,
    },
    { // 139
        tile: TileType.HOLE_EDGE,
        layer: DungeonLayer.Surface,
        startProbability: 100,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // machine components
    // commutation altars
    { // 140
        tile: TileType.COMMUTATION_ALTAR_INERT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "the items on the two altars flash with a brilliant light!",
        lightFlare: LightType.SCROLL_ENCHANTMENT_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 141
        tile: TileType.PIPE_GLOWING,
        layer: DungeonLayer.Surface,
        startProbability: 90,
        probabilityDecrement: 60,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 142
        tile: TileType.PIPE_INERT,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.SCROLL_ENCHANTMENT_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // resurrection altars
    { // 143
        tile: TileType.RESURRECTION_ALTAR_INERT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_RESURRECT_ALLY,
        description: "An old friend emerges from a bloom of sacred light!",
        lightFlare: LightType.EMPOWERMENT_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 144
        tile: TileType.MACHINE_TRIGGER_FLOOR_REPEATING,
        layer: DungeonLayer.Liquid,
        startProbability: 300,
        probabilityDecrement: 100,
        flags: DFF.DFF_SUPERPRIORITY,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.CARPET,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // sacrifice altars
    { // 145
        tile: TileType.SACRIFICE_ALTAR,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "a demonic presence whispers its demand: \"Bring to me the marked sacrifice!\"",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 146
        tile: TileType.SACRIFICE_LAVA,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "demonic cackling echoes through the room as the altar plunges downward!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 147
        tile: TileType.ALTAR_CAGE_RETRACTABLE,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // coffin bursts open to reveal vampire:
    { // 148
        tile: TileType.COFFIN_OPEN,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "the coffin opens and a dark figure rises!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.darkGray,
        effectRadius: 3,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 149
        tile: TileType.PLAIN_FIRE,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "as flames begin to lick the coffin, its tenant bursts forth!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_EMBERS_PATCH,
        messageDisplayed: false,
    },
    { // 150
        tile: TileType.MACHINE_TRIGGER_FLOOR,
        layer: DungeonLayer.Dungeon,
        startProbability: 200,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // throwing tutorial:
    { // 151
        tile: TileType.ALTAR_INERT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "the cage lifts off of the altar.",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 152
        tile: TileType.TRAP_DOOR,
        layer: DungeonLayer.Liquid,
        startProbability: 225,
        probabilityDecrement: 100,
        flags: DFF.DFF_CLEAR_OTHER_TERRAIN | DFF.DFF_SUBSEQ_EVERYWHERE,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_SHOW_TRAPDOOR_HALO,
        messageDisplayed: false,
    },
    { // 153
        tile: TileType.LAVA,
        layer: DungeonLayer.Liquid,
        startProbability: 225,
        probabilityDecrement: 100,
        flags: DFF.DFF_CLEAR_OTHER_TERRAIN,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 154
        tile: TileType.MACHINE_PRESSURE_PLATE_USED,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // rat trap:
    { // 155
        tile: TileType.RAT_TRAP_WALL_CRACKING,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "a scratching sound emanates from the nearby walls!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_RUBBLE,
        messageDisplayed: false,
    },
    // wooden barricade at entrance:
    { // 156
        tile: TileType.PLAIN_FIRE,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "flames quickly consume the wooden barricade.",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // wooden barricade around altar:
    { // 157
        tile: TileType.WOODEN_BARRICADE,
        layer: DungeonLayer.Dungeon,
        startProbability: 220,
        probabilityDecrement: 100,
        flags: DFF.DFF_TREAT_AS_BLOCKING | DFF.DFF_SUBSEQ_EVERYWHERE,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_SMALL_DEAD_GRASS,
        messageDisplayed: false,
    },
    // shallow water flood machine:
    { // 158
        tile: TileType.MACHINE_FLOOD_WATER_SPREADING,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "you hear a heavy click, and the nearby water begins flooding the area!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 159
        tile: TileType.SHALLOW_WATER,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 160
        tile: TileType.MACHINE_FLOOD_WATER_SPREADING,
        layer: DungeonLayer.Liquid,
        startProbability: 100,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.FLOOR_FLOODABLE,
        subsequentDF: DungeonFeatureType.DF_SHALLOW_WATER,
        messageDisplayed: false,
    },
    { // 161
        tile: TileType.MACHINE_FLOOD_WATER_DORMANT,
        layer: DungeonLayer.Liquid,
        startProbability: 250,
        probabilityDecrement: 100,
        flags: DFF.DFF_TREAT_AS_BLOCKING,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_SPREADABLE_DEEP_WATER_POOL,
        messageDisplayed: false,
    },
    { // 162
        tile: TileType.DEEP_WATER,
        layer: DungeonLayer.Liquid,
        startProbability: 90,
        probabilityDecrement: 100,
        flags: DFF.DFF_CLEAR_OTHER_TERRAIN | DFF.DFF_PERMIT_BLOCKING,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // unstable floor machine:
    { // 163
        tile: TileType.MACHINE_COLLAPSE_EDGE_SPREADING,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "you hear a deep rumbling noise as the floor begins to collapse!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 164
        tile: TileType.CHASM,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_CLEAR_OTHER_TERRAIN,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_SHOW_TRAPDOOR_HALO,
        messageDisplayed: false,
    },
    { // 165
        tile: TileType.MACHINE_COLLAPSE_EDGE_SPREADING,
        layer: DungeonLayer.Liquid,
        startProbability: 100,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.FLOOR_FLOODABLE,
        subsequentDF: DungeonFeatureType.DF_COLLAPSE,
        messageDisplayed: false,
    },
    { // 166
        tile: TileType.MACHINE_COLLAPSE_EDGE_DORMANT,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // levitation bridge machine:
    { // 167
        tile: TileType.CHASM_WITH_HIDDEN_BRIDGE_ACTIVE,
        layer: DungeonLayer.Liquid,
        startProbability: 100,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.CHASM_WITH_HIDDEN_BRIDGE,
        subsequentDF: DungeonFeatureType.DF_BRIDGE_APPEARS,
        messageDisplayed: false,
    },
    { // 168
        tile: TileType.CHASM_WITH_HIDDEN_BRIDGE_ACTIVE,
        layer: DungeonLayer.Liquid,
        startProbability: 100,
        probabilityDecrement: 100,
        flags: 0,
        description: "a stone bridge extends from the floor with a grinding sound.",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.CHASM_WITH_HIDDEN_BRIDGE,
        subsequentDF: DungeonFeatureType.DF_BRIDGE_APPEARS,
        messageDisplayed: false,
    },
    { // 169
        tile: TileType.STONE_BRIDGE,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 170
        tile: TileType.MACHINE_CHASM_EDGE,
        layer: DungeonLayer.Liquid,
        startProbability: 100,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // retracting lava pool:
    { // 171
        tile: TileType.LAVA_RETRACTABLE,
        layer: DungeonLayer.Liquid,
        startProbability: 100,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: TileType.LAVA,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 172
        tile: TileType.LAVA_RETRACTING,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "hissing fills the air as the lava begins to cool.",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 173
        tile: TileType.OBSIDIAN,
        layer: DungeonLayer.Surface,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_STEAM_ACCUMULATION,
        messageDisplayed: false,
    },
    // hidden poison vent machine:
    { // 174
        tile: TileType.MACHINE_POISON_GAS_VENT_DORMANT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "you notice an inactive gas vent hidden in a crevice of the floor.",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 175
        tile: TileType.MACHINE_POISON_GAS_VENT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "deadly purple gas starts wafting out of hidden vents in the floor!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 176
        tile: TileType.PORTCULLIS_CLOSED,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_EVACUATE_CREATURES_FIRST,
        description: "with a heavy mechanical sound, an iron portcullis falls from the ceiling!",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 177
        tile: TileType.PORTCULLIS_DORMANT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "the portcullis slowly rises from the ground into a slot in the ceiling.",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 178
        tile: TileType.POISON_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 25,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // hidden methane vent machine:
    { // 179
        tile: TileType.MACHINE_METHANE_VENT_DORMANT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "you notice an inactive gas vent hidden in a crevice of the floor.",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 180
        tile: TileType.MACHINE_METHANE_VENT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "explosive methane gas starts wafting out of hidden vents in the floor!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_VENT_SPEW_METHANE,
        messageDisplayed: false,
    },
    { // 181
        tile: TileType.METHANE_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 60,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 182
        tile: TileType.PILOT_LIGHT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "a torch falls from its mount and lies sputtering on the floor.",
        lightFlare: LightType.FALLEN_TORCH_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // paralysis trap:
    { // 183
        tile: TileType.MACHINE_PARALYSIS_VENT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "you notice an inactive gas vent hidden in a crevice of the floor.",
        lightFlare: LightType.GENERIC_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 184
        tile: TileType.PARALYSIS_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 350,
        probabilityDecrement: 0,
        flags: 0,
        description: "paralytic gas sprays upward from hidden vents in the floor!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_REVEAL_PARALYSIS_VENT_SILENTLY,
        messageDisplayed: false,
    },
    { // 185
        tile: TileType.MACHINE_PARALYSIS_VENT,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // thematic dungeon:
    { // 186
        tile: TileType.RED_BLOOD,
        layer: DungeonLayer.Surface,
        startProbability: 75,
        probabilityDecrement: 25,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // statuary:
    { // 187
        tile: TileType.STATUE_CRACKING,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "cracks begin snaking across the marble surface of the statue!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_RUBBLE,
        messageDisplayed: false,
    },
    { // 188
        tile: TileType.RUBBLE,
        layer: DungeonLayer.Surface,
        startProbability: 120,
        probabilityDecrement: 100,
        flags: DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "the statue shatters!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.darkGray,
        effectRadius: 3,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_RUBBLE,
        messageDisplayed: false,
    },
    // hidden turrets:
    { // 189
        tile: TileType.WALL,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "you hear a click, and the stones in the wall shift to reveal turrets!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_RUBBLE,
        messageDisplayed: false,
    },
    // worm tunnels:
    { // 190
        tile: TileType.WORM_TUNNEL_MARKER_DORMANT,
        layer: DungeonLayer.Liquid,
        startProbability: 5,
        probabilityDecrement: 5,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 1 /* GRANITE */,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 191
        tile: TileType.WORM_TUNNEL_MARKER_ACTIVE,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 192
        tile: TileType.FLOOR,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_SUPERPRIORITY | DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_TUNNELIZE,
        messageDisplayed: false,
    },
    { // 193
        tile: TileType.FLOOR,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "the nearby wall cracks and collapses in a cloud of dust!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.darkGray,
        effectRadius: 5,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_TUNNELIZE,
        messageDisplayed: false,
    },
    // haunted room:
    { // 194
        tile: TileType.DARK_FLOOR_DARKENING,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "the light in the room flickers and you feel a chill in the air.",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 195
        tile: TileType.DARK_FLOOR,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_ECTOPLASM_DROPLET,
        messageDisplayed: false,
    },
    { // 196
        tile: TileType.HAUNTED_TORCH_TRANSITIONING,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 197
        tile: TileType.HAUNTED_TORCH,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // mud pit:
    { // 198
        tile: TileType.MACHINE_MUD_DORMANT,
        layer: DungeonLayer.Liquid,
        startProbability: 100,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 199
        tile: TileType.MUD,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "across the bog, bubbles rise ominously from the mud.",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // electric crystals:
    { // 200
        tile: TileType.ELECTRIC_CRYSTAL_ON,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "the crystal absorbs the electricity and begins to glow.",
        lightFlare: LightType.CHARGE_FLASH_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 201
        tile: TileType.WALL,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "the wall above the lever shifts to reveal a spark turret!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // idyll:
    { // 202
        tile: TileType.SHALLOW_WATER,
        layer: DungeonLayer.Liquid,
        startProbability: 150,
        probabilityDecrement: 100,
        flags: DFF.DFF_PERMIT_BLOCKING,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 203
        tile: TileType.DEEP_WATER,
        layer: DungeonLayer.Liquid,
        startProbability: 90,
        probabilityDecrement: 100,
        flags: DFF.DFF_TREAT_AS_BLOCKING | DFF.DFF_CLEAR_OTHER_TERRAIN | DFF.DFF_SUBSEQ_EVERYWHERE,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_SHALLOW_WATER_POOL,
        messageDisplayed: false,
    },
    // swamp:
    { // 204
        tile: TileType.SHALLOW_WATER,
        layer: DungeonLayer.Liquid,
        startProbability: 30,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 205
        tile: TileType.GRAY_FUNGUS,
        layer: DungeonLayer.Surface,
        startProbability: 80,
        probabilityDecrement: 50,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_SWAMP_MUD,
        messageDisplayed: false,
    },
    { // 206
        tile: TileType.MUD,
        layer: DungeonLayer.Liquid,
        startProbability: 75,
        probabilityDecrement: 5,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_SWAMP_WATER,
        messageDisplayed: false,
    },
    // camp:
    { // 207
        tile: TileType.HAY,
        layer: DungeonLayer.Surface,
        startProbability: 90,
        probabilityDecrement: 87,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    { // 208
        tile: TileType.JUNK,
        layer: DungeonLayer.Surface,
        startProbability: 20,
        probabilityDecrement: 20,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // remnants:
    { // 209
        tile: TileType.CARPET,
        layer: DungeonLayer.Dungeon,
        startProbability: 110,
        probabilityDecrement: 20,
        flags: DFF.DFF_SUBSEQ_EVERYWHERE,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_REMNANT_ASH,
        messageDisplayed: false,
    },
    { // 210
        tile: TileType.BURNED_CARPET,
        layer: DungeonLayer.Surface,
        startProbability: 120,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // chasm catwalk:
    { // 211
        tile: TileType.CHASM,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_CLEAR_OTHER_TERRAIN,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_SHOW_TRAPDOOR_HALO,
        messageDisplayed: false,
    },
    { // 212
        tile: TileType.STONE_BRIDGE,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_CLEAR_OTHER_TERRAIN,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // lake catwalk:
    { // 213
        tile: TileType.DEEP_WATER,
        layer: DungeonLayer.Liquid,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: DFF.DFF_CLEAR_OTHER_TERRAIN,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_LAKE_HALO,
        messageDisplayed: false,
    },
    { // 214
        tile: TileType.SHALLOW_WATER,
        layer: DungeonLayer.Liquid,
        startProbability: 160,
        probabilityDecrement: 100,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // worms pop out of walls:
    { // 215
        tile: TileType.RUBBLE,
        layer: DungeonLayer.Surface,
        startProbability: 120,
        probabilityDecrement: 100,
        flags: DFF.DFF_ACTIVATE_DORMANT_MONSTER,
        description: "the nearby wall explodes in a shower of stone fragments!",
        lightFlare: LightType.NO_LIGHT,
        flashColor: C.darkGray,
        effectRadius: 3,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_RUBBLE,
        messageDisplayed: false,
    },
    // monster cages open:
    { // 216
        tile: TileType.MONSTER_CAGE_OPEN,
        layer: DungeonLayer.Dungeon,
        startProbability: 0,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: 0,
        messageDisplayed: false,
    },
    // goblin warren:
    { // 217
        tile: TileType.STENCH_SMOKE_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 50,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_PLAIN_FIRE,
        messageDisplayed: false,
    },
    { // 218
        tile: TileType.STENCH_SMOKE_GAS,
        layer: DungeonLayer.Gas,
        startProbability: 50,
        probabilityDecrement: 0,
        flags: 0,
        description: "",
        lightFlare: LightType.NO_LIGHT,
        flashColor: null,
        effectRadius: 0,
        propagationTerrain: 0,
        subsequentDF: DungeonFeatureType.DF_EMBERS,
        messageDisplayed: false,
    },
];

