#!/usr/bin/env npx tsx
/**
 * Port Health Reporter — cross-references the C manifest with the TS stub
 * report to produce a port health dashboard.
 *
 * Reads:
 *   docs/analysis/c-manifest.json   (static, committed)
 *   docs/analysis/stub-report.json  (generated by scan-stubs.ts)
 *
 * Produces:
 *   docs/analysis/port-health.json  (structured data)
 *   docs/analysis/PORT_HEALTH.md    (human-readable summary)
 *
 * Usage: npx tsx tools/analysis/port-health.ts
 */

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, resolve, relative } from 'path';

const REPO_ROOT = resolve(import.meta.dirname, '../..');
const ANALYSIS_DIR = join(REPO_ROOT, 'docs/analysis');
const TS_SRC = join(REPO_ROOT, 'rogue-ts/src');

const GAME_LOOP_ROOTS = [
  'playerMoves', 'processMonsters', 'monstersTurn', 'updateEnvironment',
  'initializeLevel', 'startLevel', 'gameLoop', 'mainBrogueJunction',
  'rogueMain', 'initializeRogue',
];

interface CManifest {
  generated: string;
  stats: { totalFunctions: number; totalCallEdges: number; totalSystems: number };
  systems: Record<string, string[]>;
  functions: Record<string, {
    file: string; line: number; endLine: number; returnType: string;
    system: string; params: { name: string; type: string }[];
    callers: string[]; callees: string[];
  }>;
}

interface StubReport {
  scanned: string;
  stats: { totalStubs: number; uniqueStubNames: number; filesWithStubs: number; contextBuilders: number };
  stubs: { file: string; line: number; property: string; stubType: string; contextBuilder: string }[];
  byFunction: Record<string, { stubCount: number; locations: string[] }>;
  byContextBuilder: Record<string, { total: number; stubs: string[] }>;
}

function scanCComments(): Map<string, string> {
  const map = new Map<string, string>();
  const tsFiles = collectTsFiles(TS_SRC);
  const commentRegex = /\/\/\s*C:\s*(\w+)\s*\(\)/g;

  for (const file of tsFiles) {
    const text = readFileSync(file, 'utf8');
    let match;
    while ((match = commentRegex.exec(text)) !== null) {
      map.set(match[1], relative(join(REPO_ROOT, 'rogue-ts'), file));
    }
  }
  return map;
}

function collectTsFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...collectTsFiles(full));
    else if (entry.name.endsWith('.ts') && !entry.name.endsWith('.test.ts') && !entry.name.endsWith('.d.ts')) {
      files.push(full);
    }
  }
  return files;
}

function isOnCriticalPath(funcName: string, manifest: CManifest, visited = new Set<string>()): boolean {
  if (GAME_LOOP_ROOTS.includes(funcName)) return true;
  if (visited.has(funcName)) return false;
  visited.add(funcName);

  const fn = manifest.functions[funcName];
  if (!fn) return false;

  for (const caller of fn.callers) {
    if (isOnCriticalPath(caller, manifest, visited)) return true;
  }
  return false;
}

const manifest: CManifest = JSON.parse(readFileSync(join(ANALYSIS_DIR, 'c-manifest.json'), 'utf8'));
const stubReport: StubReport = JSON.parse(readFileSync(join(ANALYSIS_DIR, 'stub-report.json'), 'utf8'));

const cCommentMap = scanCComments();

const stubbedNames = new Set(Object.keys(stubReport.byFunction));
const cFunctionNames = new Set(Object.keys(manifest.functions));

const matchedToCFunction: Record<string, string> = {};
for (const stubName of stubbedNames) {
  if (cFunctionNames.has(stubName)) {
    matchedToCFunction[stubName] = stubName;
  } else if (cCommentMap.has(stubName)) {
    matchedToCFunction[stubName] = stubName;
  }
}

const criticalStubs: {
  name: string;
  cFunction: string;
  system: string;
  cCallers: string[];
  stubLocations: number;
  reason: string;
}[] = [];

for (const [stubName, cFuncName] of Object.entries(matchedToCFunction)) {
  const cFunc = manifest.functions[cFuncName];
  if (!cFunc) continue;

  if (isOnCriticalPath(cFuncName, manifest)) {
    const gameLoopCallers = cFunc.callers.filter(c => GAME_LOOP_ROOTS.includes(c));
    const reason = gameLoopCallers.length > 0
      ? `Direct callee of ${gameLoopCallers.join(', ')}`
      : `Reachable from game loop via call chain`;

    criticalStubs.push({
      name: stubName,
      cFunction: cFuncName,
      system: cFunc.system,
      cCallers: cFunc.callers,
      stubLocations: stubReport.byFunction[stubName].stubCount,
      reason,
    });
  }
}

criticalStubs.sort((a, b) => b.stubLocations - a.stubLocations);

const bySystems: Record<string, { total: number; stubbed: number; critical: number; stubbedNames: string[] }> = {};
for (const [system, funcNames] of Object.entries(manifest.systems)) {
  const systemStubbed = funcNames.filter(n => stubbedNames.has(n));
  const systemCritical = systemStubbed.filter(n => criticalStubs.some(cs => cs.cFunction === n));
  bySystems[system] = {
    total: funcNames.length,
    stubbed: systemStubbed.length,
    critical: systemCritical.length,
    stubbedNames: systemStubbed.sort(),
  };
}

const healthReport = {
  generated: new Date().toISOString(),
  summary: {
    cFunctions: manifest.stats.totalFunctions,
    uniqueStubNames: stubReport.stats.uniqueStubNames,
    matchedToCFunctions: Object.keys(matchedToCFunction).length,
    criticalStubbed: criticalStubs.length,
    totalStubOccurrences: stubReport.stats.totalStubs,
    contextBuildersWithStubs: stubReport.stats.contextBuilders,
  },
  bySystems,
  criticalStubs,
  matchedToCFunction,
};

writeFileSync(join(ANALYSIS_DIR, 'port-health.json'), JSON.stringify(healthReport, null, 2) + '\n');

const md = generateMarkdown(healthReport, stubReport);
writeFileSync(join(ANALYSIS_DIR, 'PORT_HEALTH.md'), md);

console.log(`Port health report: ${join(ANALYSIS_DIR, 'port-health.json')}`);
console.log(`Markdown summary:   ${join(ANALYSIS_DIR, 'PORT_HEALTH.md')}`);
console.log('');
console.log(`  C functions: ${healthReport.summary.cFunctions}`);
console.log(`  Unique stub names: ${healthReport.summary.uniqueStubNames}`);
console.log(`  Matched to C functions: ${healthReport.summary.matchedToCFunctions}`);
console.log(`  Critical (on game loop path): ${healthReport.summary.criticalStubbed}`);
console.log(`  Total stub occurrences: ${healthReport.summary.totalStubOccurrences}`);

function generateMarkdown(
  health: typeof healthReport,
  stubs: StubReport,
): string {
  const lines: string[] = [];
  const w = (s: string) => lines.push(s);

  w('# Port Health Report');
  w('');
  w(`Generated: ${health.generated}`);
  w('');
  w('## Summary');
  w('');
  w(`| Metric | Count |`);
  w(`| --- | ---: |`);
  w(`| C functions (total) | ${health.summary.cFunctions} |`);
  w(`| Unique stub names in TS | ${health.summary.uniqueStubNames} |`);
  w(`| Stubs matching a C function | ${health.summary.matchedToCFunctions} |`);
  w(`| Critical stubs (game-loop reachable) | ${health.summary.criticalStubbed} |`);
  w(`| Total stub occurrences | ${health.summary.totalStubOccurrences} |`);
  w(`| Context builders with stubs | ${health.summary.contextBuildersWithStubs} |`);
  w('');
  w('## System Breakdown');
  w('');
  w('| System | C Functions | Stubbed | Critical | % Stubbed |');
  w('| --- | ---: | ---: | ---: | ---: |');

  const sortedSystems = Object.entries(health.bySystems)
    .sort((a, b) => b[1].stubbed - a[1].stubbed);

  for (const [system, data] of sortedSystems) {
    if (data.stubbed === 0) continue;
    const pct = ((data.stubbed / data.total) * 100).toFixed(0);
    w(`| ${system} | ${data.total} | ${data.stubbed} | ${data.critical} | ${pct}% |`);
  }

  w('');
  w('## Critical Stubs');
  w('');
  w('Functions that are stubbed in TS and reachable from the game loop in C.');
  w('');

  if (criticalStubs.length === 0) {
    w('None found.');
  } else {
    w('| Function | System | Stub Locations | Reason |');
    w('| --- | --- | ---: | --- |');
    for (const cs of criticalStubs.slice(0, 40)) {
      w(`| ${cs.name} | ${cs.system} | ${cs.stubLocations} | ${cs.reason} |`);
    }
    if (criticalStubs.length > 40) {
      w(`| ... | ... | ... | ${criticalStubs.length - 40} more |`);
    }
  }

  w('');
  w('## Most-Stubbed Context Builders');
  w('');
  w('| Context Builder | Stub Count | Unique Stubs |');
  w('| --- | ---: | ---: |');

  const sortedBuilders = Object.entries(stubs.byContextBuilder)
    .sort((a, b) => b[1].total - a[1].total)
    .slice(0, 15);

  for (const [name, data] of sortedBuilders) {
    w(`| ${name} | ${data.total} | ${data.stubs.length} |`);
  }

  w('');
  w('## Most-Repeated Stubs');
  w('');
  w('Functions stubbed in the most context builders.');
  w('');
  w('| Function | Occurrences |');
  w('| --- | ---: |');

  const sortedFuncs = Object.entries(stubs.byFunction)
    .sort((a, b) => b[1].stubCount - a[1].stubCount)
    .slice(0, 20);

  for (const [name, data] of sortedFuncs) {
    w(`| ${name} | ${data.stubCount} |`);
  }

  w('');
  w('---');
  w('');
  w('*Regenerate: `cd tools/analysis && npx tsx port-health.ts`*');
  w('');

  return lines.join('\n');
}
